# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NamedProject_Testical.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(634, 441)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(220, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(490, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(540, 10, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 10, 113, 31))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 50, 631, 411))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.link_2 = QtWidgets.QLabel(self.frame)
        self.link_2.setGeometry(QtCore.QRect(30, 140, 81, 81))
        self.link_2.setText("")
        self.link_2.setObjectName("link_2")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_8.setGeometry(QtCore.QRect(70, 350, 541, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 350, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(80, 350, 95, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(200, 350, 95, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_3.setGeometry(QtCore.QRect(330, 350, 95, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_4.setGeometry(QtCore.QRect(460, 350, 95, 20))
        self.radioButton_4.setObjectName("radioButton_4")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(270, 10, 201, 31))
        self.lineEdit.setInputMask("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(10, 60, 611, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "PN"))
        self.label.setText(_translate("Dialog", "type:"))
        self.label_2.setText(_translate("Dialog", "scorr:"))
        self.lineEdit_2.setText(_translate("Dialog", "0"))
        self.lineEdit_3.setText(_translate("Dialog", "1"))
        self.label_6.setText(_translate("Dialog", "answer:"))
        self.radioButton.setText(_translate("Dialog", "Opt1"))
        self.radioButton_2.setText(_translate("Dialog", "Opt1"))
        self.radioButton_3.setText(_translate("Dialog", "Opt1"))
        self.radioButton_4.setText(_translate("Dialog", "Opt1"))
        self.lineEdit.setText(_translate("Dialog", "Test"))
        self.label_3.setText(_translate("Dialog", "number:"))
        self.pushNext = QtWidgets.QPushButton('Next',Dialog)
        self.pushNext.move(520,370)
        self.Sc = 0
        self.Nu = 1
        self.carncy = ''
        self.Cond = []
        self.radioButton.clicked.connect(self.po1)
        self.radioButton_2.clicked.connect(self.po2)
        self.radioButton_3.clicked.connect(self.po3)
        self.radioButton_4.clicked.connect(self.po4)
        self.lineEdit_8.setReadOnly(True)
        self.pushNext.clicked.connect(self.nextq)
        self.Truler = []
        self.Falser = []
        self.Name = []
        self.pushNext.close()
        
    def nextq(self):
        self.pushNext.close()
        self.radioButton.setEnabled(True)
        self.radioButton_2.setEnabled(True)
        self.radioButton_3.setEnabled(True)
        self.radioButton_4.setEnabled(True)
        self.info = self.info[6:]
        nq = []
        nq.extend(self.Truler)
        nq.extend(self.Falser)
        self.lineEdit_3.setText(str(len(nq)))
        self.maps()
        
    def map_str(self,info:list):
        self.info = info
    def maps(self):
        try:
            self.scorr = self.info[1]
            self.lineEdit_2.setText(self.scorr)
            que = self.info[2]
            self.que = que
            self.plainTextEdit_3.setPlainText(que)
            options = self.info[3]
            self.o1,self.o2,self.o3,self.o4,oc = options.split('--')
            print(oc)
            self.carncy = oc
            self.radioButton.setText(self.o1)
            self.radioButton_2.setText(self.o2)
            self.radioButton_3.setText(self.o3)
            self.radioButton_4.setText(self.o4)
            image = self.info[4]
            print(image.split('--'))
            adr,mx,my,sx,sy = image.split('--')
            self.link_2.clear()
            
            if adr != '':
                soho = QtGui.QPixmap(adr)
                mx,my = int(mx),int(my)
                sx,sy = int(sx),int(sy)
                self.link_2.setPixmap(soho)
                self.link_2.move(mx,my)
                self.link_2.resize(sx,sy)
                self.link_2.setScaledContents(True)
        except:
            try:
                from Karname import Ui_Dialog
                samdi = Ui_Dialog()
                diaKaR = QtWidgets.QDialog()
                samdi.setupUi(diaKaR)
                diaKaR.setWindowTitle(self.Name[0])
                quss = []
                quss.extend(self.Truler)
                quss.extend(self.Falser)
                Nq = len(quss)
                ca = len(self.Truler)
                SumScorrDarsad = ca * 100 / Nq
                samdi.args(Trues = self.Truler, Falses = self.Falser, SumScorr = self.Sc, SumScorrDarsad = SumScorrDarsad,Nt = len(self.Truler), Nf = len(self.Falser), type_ = 'Test', Quss = quss)
                diaKaR.exec_()
            except:
                from Out import Ui_Dialog
                ic = Ui_Dialog()
                diaer = QtWidgets.QDialog()
                ic.setupUi(diaer)
                ic.label.setText('Erorr:Erorr in analisys data')
                ic.pushButton.clicked.connect(diaer.close)
                diaer.exec_()
    def po1(self):
        try:
            self.pushNext.show()
            if self.o1 == self.carncy:
                self.Sc += float(self.scorr)
                self.Cond.append('True')
                self.Truler.append(self.que)
                print('Carrect')
            if self.o1 != self.carncy:
                self.Cond.append('False')
                self.Falser.append(self.que)
            self.radioButton.setEnabled(False)
            self.radioButton_2.setEnabled(False)
            self.radioButton_3.setEnabled(False)
            self.radioButton_4.setEnabled(False)
            print(self.Cond)
        except:
            from Out import Ui_Dialog
            ic = Ui_Dialog()
            diaer = QtWidgets.QDialog()
            ic.setupUi(diaer)
            font = QtGui.QFont()
            font.setPointSize(16)
            ic.label.setFont(font)
            ic.label.setText('Erorr:Erorr in Opt what is data?')
            ic.pushButton.clicked.connect(diaer.close)
            diaer.exec_()
    def po2(self):
        try:
             self.pushNext.show()
             if self.o2 == self.carncy:
                 self.Sc += float(self.scorr)
                 self.Cond.append('True')
                 self.Truler.append(self.que)
                 print('Carrect')
             if self.o2 != self.carncy:
                 self.Cond.append('False')
                 self.Falser.append(self.que)
             self.radioButton.setEnabled(False)
             self.radioButton_2.setEnabled(False)
             self.radioButton_3.setEnabled(False)
             self.radioButton_4.setEnabled(False)
             print(self.Cond)
        except:
            from Out import Ui_Dialog
            ic = Ui_Dialog()
            diaer = QtWidgets.QDialog()
            ic.setupUi(diaer)
            font = QtGui.QFont()
            font.setPointSize(16)
            ic.label.setFont(font)
            ic.label.setText('Erorr:Erorr in Opt what is data?')
            ic.pushButton.clicked.connect(diaer.close)
            diaer.exec_()
    def po3(self):
        try:
             self.pushNext.show()
             if self.o3 == self.carncy:
                 self.Sc += float(self.scorr)
                 self.Cond.append('True')
                 self.Truler.append(self.que)
                 print('Carrect')
             if self.o3 != self.carncy:
                 self.Cond.append('False')
                 self.Falser.append(self.que)
             self.radioButton.setEnabled(False)
             self.radioButton_2.setEnabled(False)
             self.radioButton_3.setEnabled(False)
             self.radioButton_4.setEnabled(False)
             print(self.Cond)
        except:
            from Out import Ui_Dialog
            ic = Ui_Dialog()
            diaer = QtWidgets.QDialog()
            ic.setupUi(diaer)
            font = QtGui.QFont()
            font.setPointSize(16)
            ic.label.setFont(font)
            ic.label.setText('Erorr:Erorr in Opt what is data?')
            ic.pushButton.clicked.connect(diaer.close)
            diaer.exec_()
    def po4(self):
        try:
             self.pushNext.show()
             if self.o4 == self.carncy:
                 self.Sc += float(self.scorr)
                 self.Cond.append('True')
                 self.Truler.append(self.que)
                 print('Carrect')
             if self.o4 != self.carncy:
                 self.Cond.append('False')
                 self.Falser.append(self.que)
             self.radioButton.setEnabled(False)
             self.radioButton_2.setEnabled(False)
             self.radioButton_3.setEnabled(False)
             self.radioButton_4.setEnabled(False)
             print(self.Cond)
        except:
            from Out import Ui_Dialog
            ic = Ui_Dialog()
            diaer = QtWidgets.QDialog()
            ic.setupUi(diaer)
            font = QtGui.QFont()
            font.setPointSize(16)
            ic.label.setFont(font)
            ic.label.setText('Erorr:Erorr in Opt what is data?')
            ic.pushButton.clicked.connect(diaer.close)
            diaer.exec_()
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
