# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Open.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 98)
        Dialog.setMinimumSize(QtCore.QSize(400, 98))
        Dialog.setMaximumSize(QtCore.QSize(401, 99))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 371, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 60, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        with open('titleOP.txt')as title:
            title = title.read()
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog",title))
        self.lineEdit.setText(_translate("Dialog", "adress"))
        
        self.pushButton.setText(_translate("Dialog", "open"))
        self.pushButton.clicked.connect(lambda : self.setadrs())
    def setadrs(self):
        print('0.line')
        adr = self.lineEdit.text()
        print('1.line')
        from collections import deque
        print('2.line')
        dq = deque(list(adr))
        print('3.line')
        if adr[:1] == '"':
            dq.popleft()
        print('4.line')
        if adr[-1:] == '"':
            dq.pop()
        print('5.line')
        adr = ''.join(dq)
        print('6.line')
        from Compiler import Ui_Dialog,setAdrFile
        print('7.line')
        uidd = Ui_Dialog()
        print('8.line')
        diadss = QtWidgets.QDialog()
        print('9.line')
        setAdrFile.append(adr)
        print('10.line')
        uidd.setupUi(diadss)
        uidd.pushButton_3.clicked.connect(lambda : diadss.close())
        uidd.pushButton.clicked.connect(lambda : diadss.close())
        print('11.line')
        diadss.exec_()
        print('12.line')
        setAdrFile.clear()
    



